import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "lenis/dist/lenis.css"
import "./globals.css"
import LenisProvider from "@/components/lenis-provider"

// DEV-ONLY cache bypass — REMOVE before production. See memory/CLAUDE.md.
export const dynamic = "force-dynamic"
export const fetchCache = "force-no-store"
export const revalidate = 0

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <LenisProvider>{children}</LenisProvider>
      </body>
    </html>
  )
}
